apiVersion: v2
name: rtg-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    condition: mongodb.enabled
    version: 13.6.0
    repository: "https://charts.bitnami.com/bitnami"
